(define (cube x) (* x x x))
(define (inc a) (+ a 1))
(define (integral f a b n) 
  (define h (/ (- b a) n))
  (define (yk k) (f (+ a (* k h))))
  (define (term k)
    (* (cond ((or (= k 0) (= k n)) 1)
	     ((odd? k) 4)
	     (else 2))
       (yk k)))
  (* (/ h 3) (sum term 0 inc n)))
