(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
    (report-prime(- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(define (odd? n) (= (remainder n 2) 1))
(define (search-for-primes begin counter)
  (if (odd? begin) (sfp begin counter) (sfp (+ begin 1) counter)))
  (define (sfp cur counter) (if (> counter 0) 
			   (if (timed-prime-test cur) (sfp (+ 2 cur) (- 1 counter)) (sfp (+ 2 cur) counter)) 
			   ))
