(define (install-sheme-zero-package)
  (put 'zero? 'scheme-number zero?))
(define (install-complex-zero-package)
  (define (zero? x)
    (and (= (real-part x) 0) (= (imag-part x) 0)))
  (put 'zero? 'complex zero?)
  'done)
(define (install-rational-zero-package)
  (define (zero? x)
    (= (number x) 0))
  (put 'zero? 'rational zero?)
  'done)
