(define (type-tag x)
  (cond ((number? x)) '(scheme-number)
	((pair? x) (car x))
	(else (error "no such shit"))))
(define (contents x)
  (if ((eq? (type-tag x) '(scheme-number)) x)
    ((pair? x) (cadr x))
    (else (error "no such kind"))))
(define (attach-tag tag x)
  (cond ((eq? tag 'scheme-number) x)
	((pair? x) (cons tag x))))
