(define (adjoin-term term term-list)
  (let ((o-term (car term))
	(c-term (cdr term)))
    (define (iter-insert term-list times)
      (if (= times o-term)
	(cons (+ (car term-list) c-term) (cdr term-list))
	(cons (car term-list) (iter-insert (cdr term-list) (- times 1)))))
    (iter-insert term-list (- (length term-list) 1))))
(define (the-empty-termlist) '())
(define (first-term term-list)
  (cons (- (length term-list) 1) (cons term-list)))
(define (rest-terms term-list) (cdr term-list))
(define (empty-termlist? x)
  (null? x))
(define (make-term order coeff)
  (cons order coeff))
(define (order term)
  (car term))
(define (coeff term)
  (cdr term))
(这个包里面的加减号应换为add 和 sub，由于调试的缘故，所以没有换，因为还不会put和get的程序写法。）
