;;;(load "ex3.70.scm")
(define weight (lambda (x) (+ (* (car x) (car x) (car x))
			      (* (cadr x) (cadr x) (cadr x)))))
(define obj (weighted-pairs integers integers weight))
(define (rama-num seq)
  (let ((former (stream-car seq))
	(later (stream-car (stream-cdr seq))))
    (if (= (weight former) (weight later))
      (cons-stream (weight former) (rama-num (stream-cdr (stream-cdr seq))))
      (rama-num (stream-cdr seq)))))
