(define (make-account total passward)
  (let ((counter 0))
  (define (withdraw x pass)
    (if (eq? pass passward)
      (if (>= total x)
	(begin (set! total (- total x)) total)
	"Insufficient funds")
      (begin (set! counter (+ 1 counter)) (if (>= counter 7) (call-the-cobs)
					    "Wrong Password!"))))
  (define (deposit x pass)
    (if (eq? pass passward)
      (begin (set! total (+ total x)) total)
      (begin (set! counter (+ 1 counter)) (if (>= counter 7) (call-the-cobs)
					    "Wrong Password!"))))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
	  ((eq? m 'deposit) deposit)
	  ((eq? m 'call-the-cobs) (call-the-cobs))
	  (else "Sorry What the fuck do you want to do?")))
  (define (call-the-cobs)
    "fuck you fuck you fuck you!!!!!")
    dispatch))
(define (make-account1 total passward)
  (define (withdraw x)
    (if (>= total x)
      (begin (set! total (- total x)) total)
      "Insufficient funds"))
  (define (deposit x)
    (set! total (+ total x))
    total)
  (define (dispatch m pass)
    (if (eq? pass passward)
      (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    (else "fuck you"))
      "Wrong Password ASSHOLE!!!"))
  dispatch)

      
