(load "steram-pac")
(define (make-zero-crossings input-stream last-value last-avpt)
  (let ((avpt (/ (+ last-value (stream-car input-stream)) 2)))
    (cons-stream (signa-change-detector avpt last-avpt)
		 (make-zero-crossing (stream-cdr input-stream)
				     (stream-car input-stream)
				     avpt))))
