(define (make-account balance num)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
	     balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    ((eq? m 'serializer) balance-serializer)
	    ((eq? m 'rank) num)
	    (else (error "Unknown request -- MAKE+ACCOUNT"
			 m))))
    dispatch))
(define (serialized-exchange a1 a2)
  (let ((serializer1 (a1 'serializer))
	(serializer2 (a2 'serializer)))
    (if (> (a1 'rank) (a2 'rank))
      ((serialzer1 (serializer2 exchange))
       a1
       a2)
      ((serialzer2 (serializer1 exchange))
       a1
       a2))))
