(define (daughter-father)
  (let ((Gabrielle (amb 'Hall 'Downing))
	(Lorna (amb 'Hall 'Downing 'Parker))
	(Rosalind (amb 'Downing 'Parker))
	(Mary 'Moore)
	(Mellissa 'Barnacle))
    (require (cond ((eq? Gabrielle 'Hall) (eq? Rosalind 'Parker))
		   ((eq? Gabrielle 'Downing) (eq? Melissa 'Parker))
		   (else false)))
    (require (distinct? (list Gabrielle Lorna Rosalind Mary Mellissa)))
    (list (list 'Gabrielle Gabrielle)
	  (list 'Lorna Lorna)
	  (list 'Rosalind Rosalind)
	  (list 'Mary Mary)
	  (list 'Mellissa Mellissa))))
