(define the-empty-env '())
(define (unbound? exp)
  (tagged-list? exp 'unbound))
(define (unbind-variable exp env)
  (make-unbound (cadr exp) env))
(define (make-unbound var env)
  (let ((vars (frame-variables (first-frame env)))
	(vals (frame-values (first-frame env))))
    (define (scan vars vals newvars newvals)
      (cond ((null? vars)
	     (error "variable doesn't exist" var))
	    ((eq? var (car vars))
	     (set-car! env (cons (append newvars (cdr vars))
				 (append newvals (cdr vals)))))
	    (else (scan (cdr vars) (cdr vals) (cons (car vars) newvars))
			(cons (car vals) newvals))))
    (scan vars vals '() '())))
