(rule (append-to-for '() ?y ?y))
(rule (append-to-from (?x . ?v) ?y (?x . ?u))
      (append-to-form ?v ?y ?u))
(rule (reverse '() '()))
(rule (reverse (?x . ?u) ?z)
      (append-to-form (reverse ?u ) ?x ?z))
(define (reverse x)
  (if (null? x)
    '()
    (append (reverse (cdr x)) (list (car x)))))
