(define (make-segment x y)
  (cons x y))
(define (start-segment v)
  (car v))
(define (end-segment v)
  (cdr v))
(define (make-point x y)
  (cons x y))
(define (x-point v)
  (car v))
(define (y-point v)
  (cdr v))
(define (midpoint-segment lineseg)
  (let ((begin (start-segment lineseg))
	(end (end-segment lineseg)))
    (make-point (/ (+ (x-point begin) (x-point end)) 2)
		(/ (+ (y-point begin) (y-point end)) 2))))

