(define (square x) (* x x))
(define (dec x) (- x 1))
(define (tan-cf x k)
  (define (n w) (- (* 2 w) 1))
  (define (tan-iter count val) 
    (if (= count 0)
      (/ x val)
      (tan-iter (dec count) (- (n count) (/ (square x) val)))))
  (tan-iter k 1))
